### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by Serithul** [ReyDonovan/LegacyCoreLegion#1]
**Description:**

When compiling the core, 3 errors occur making the core fail to compile 3 projects.

**Current behaviour:**

![image](https://user-images.githubusercontent.com/62258982/80829847-95ceee80-8bf0-11ea-9af7-d1e100b4c806.png)

If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. Download the core
2. Configure + Generate with Cmake 3_15_4/Boost 1_67_00
3. Compile with Visual Studio 2017

**Branch(es):**

Master

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** Windows 10 Pro x64

**Comment by ReyDonovan** [comment]
@Serithul I know. I will fix this when I completely upgrade with the master TC branch

**Comment by Serithul** [comment]
@ReyDonovan alright then. I'm terribly sorry for bothering you right away.
